### ISSUE TITLE
Main.c tasks are non-responsive/out-of-order

### ISSUE THREAD

**Issue by hcshires** [M2I-CySat/CySat-1-Main#30]
The mutexes from CMSIS RTOS need to be created inside a thread. All of the startup procedures need threads and mutexes to exist. The main task in AppTasks.c will be used for startup procedures that require threading. 

The threads using different priorities or that need delay need to use osDelay() and NOT HAL_DELAY(). It's ok to use HAL Delay before looping or thread initialization, but don't use it after as it doesn't let threads have processing time/takes priority over them (don't listen to them listen to ME only).

Finally, a mutex cannot be used before its corresponding thread is created.

**Comment by UltimateSteve99** [comment]
Program has been committed and Main thread properly runs while loop LED debug test. Mutexes and threads have been moved, will implement other threads as needed
